const express=require('express');
const pool=require('../config/database');
const {requireAuth,requireMfa,requireAdministrator,requireSuperuser,verifyCsrf}=require('../middleware/security');
const {validateCompany,validateMembership}=require('../validation/administration');
const audit=require('../services/audit');
const router=express.Router();
router.use(requireAuth,requireMfa,requireAdministrator);

router.get('/superuser-dashboard',requireSuperuser,async(req,res,next)=>{try{const tenantId=req.company.tenantId;const [[summary]]=await pool.execute(`SELECT
  (SELECT COUNT(*) FROM companies WHERE tenant_id=? AND status='active') AS activeCompanies,
  (SELECT COUNT(DISTINCT u.id) FROM users u JOIN company_memberships m ON m.user_id=u.id JOIN companies c ON c.id=m.company_id WHERE c.tenant_id=? AND c.status='active' AND u.status='active' AND m.status='active') AS activeUsers,
  (SELECT COUNT(*) FROM electronic_invoices i JOIN companies c ON c.id=i.company_id WHERE c.tenant_id=? AND i.status='authorized') AS issuedInvoices`,[tenantId,tenantId,tenantId]);const [usage]=await pool.execute(`SELECT 'invoicing' AS moduleName,'Facturación' AS label,COUNT(*) AS records FROM electronic_invoices x JOIN companies c ON c.id=x.company_id WHERE c.tenant_id=?
UNION ALL SELECT 'crm','CRM',COUNT(*) FROM crm_opportunities x JOIN companies c ON c.id=x.company_id WHERE c.tenant_id=?
UNION ALL SELECT 'quotations','Cotizaciones',COUNT(*) FROM crm_quotes x JOIN companies c ON c.id=x.company_id WHERE c.tenant_id=?
UNION ALL SELECT 'orders','Pedidos',COUNT(*) FROM sales_orders x JOIN companies c ON c.id=x.company_id WHERE c.tenant_id=?
UNION ALL SELECT 'receivables','Cobros',COUNT(*) FROM accounts_receivable x JOIN companies c ON c.id=x.company_id WHERE c.tenant_id=?
UNION ALL SELECT 'clients','Clientes',COUNT(*) FROM clients x JOIN companies c ON c.id=x.company_id WHERE c.tenant_id=?
UNION ALL SELECT 'articles','Artículos',COUNT(*) FROM articles x JOIN companies c ON c.id=x.company_id WHERE c.tenant_id=?
UNION ALL SELECT 'pos','POS',COUNT(*) FROM articles x JOIN companies c ON c.id=x.company_id WHERE c.tenant_id=? AND x.status='active' AND x.available_in_pos=TRUE`,Array(8).fill(tenantId));const [companies]=await pool.execute(`SELECT c.id,c.legal_name AS legalName,c.trade_name AS tradeName,COUNT(DISTINCT CASE WHEN m.status='active' AND u.status='active' THEN u.id END) AS activeUsers,COUNT(DISTINCT CASE WHEN i.status='authorized' THEN i.id END) AS issuedInvoices FROM companies c LEFT JOIN company_memberships m ON m.company_id=c.id LEFT JOIN users u ON u.id=m.user_id LEFT JOIN electronic_invoices i ON i.company_id=c.id WHERE c.tenant_id=? AND c.status='active' GROUP BY c.id ORDER BY c.legal_name`,[tenantId]);const modules=usage.map(item=>({...item,records:Number(item.records),active:Number(item.records)>0}));return res.json({summary:{activeCompanies:Number(summary.activeCompanies),modulesInUse:modules.filter(item=>item.active).length,activeUsers:Number(summary.activeUsers),issuedInvoices:Number(summary.issuedInvoices)},modules,companies:companies.map(company=>({...company,activeUsers:Number(company.activeUsers),issuedInvoices:Number(company.issuedInvoices)}))});}catch(error){return next(error);}});
router.use('/companies',(req,res,next)=>{if(req.method!=='POST'||req.authUser.is_superuser)return next();return res.status(403).json({error:'Solo el superusuario puede crear empresas.'});});
router.use('/memberships',(req,res,next)=>{if(req.method==='GET'||req.body?.role!=='administrator'||req.authUser.is_superuser)return next();return res.status(403).json({error:'Solo el superusuario puede asignar administradores de empresa.'});});
router.use('/memberships/:userId',async(req,res,next)=>{if(req.method!=='PUT'||req.authUser.is_superuser)return next();try{const userId=Number(req.params.userId);if(!Number.isSafeInteger(userId))return next();const [rows]=await pool.execute('SELECT role FROM company_memberships WHERE company_id=? AND user_id=? LIMIT 1',[req.company.id,userId]);if(rows[0]?.role==='administrator')return res.status(403).json({error:'Solo el superusuario puede modificar administradores de empresa.'});return next();}catch(error){return next(error);}});

router.get('/companies',async(req,res,next)=>{try{const [companies]=await pool.execute(`SELECT c.id,c.legal_name AS legalName,c.trade_name AS tradeName,c.ruc,c.dv,c.status,c.created_at AS createdAt,COUNT(CASE WHEN m.status='active' THEN 1 END) AS activeMembers FROM companies c LEFT JOIN company_memberships m ON m.company_id=c.id WHERE c.tenant_id=? GROUP BY c.id ORDER BY c.legal_name`,[req.company.tenantId]);return res.json({companies,activeCompanyId:req.company.id});}catch(error){return next(error);}});

router.post('/companies',verifyCsrf,async(req,res,next)=>{const validation=validateCompany(req.body);if(validation.errors)return res.status(422).json({error:'Revisa los datos de la empresa.',details:validation.errors});const v=validation.value,connection=await pool.getConnection();try{await connection.beginTransaction();const [result]=await connection.execute("INSERT INTO companies (tenant_id,legal_name,trade_name,ruc,dv,status) VALUES (?,?,?,?,?,'active')",[req.company.tenantId,v.legalName,v.tradeName,v.ruc,v.dv]);await connection.execute("INSERT INTO company_memberships (company_id,user_id,role,status) VALUES (?,?,'administrator','active')",[result.insertId,req.authUser.id]);await connection.commit();await audit(req,'company.created','company',result.insertId);return res.status(201).json({message:'Empresa creada. Ya puedes cambiar a ella desde el selector superior.',id:result.insertId});}catch(error){await connection.rollback();return next(error);}finally{connection.release();}});

router.get('/memberships',async(req,res,next)=>{try{const [memberships]=await pool.execute(`SELECT u.id AS userId,u.full_name AS fullName,u.email,m.role,m.status,m.created_at AS createdAt FROM company_memberships m JOIN users u ON u.id=m.user_id WHERE m.company_id=? ORDER BY u.full_name`,[req.company.id]);return res.json({memberships,company:{id:req.company.id,name:req.company.name}});}catch(error){return next(error);}});

router.post('/memberships',verifyCsrf,async(req,res,next)=>{const validation=validateMembership({...req.body,status:'active'});if(validation.errors)return res.status(422).json({error:'Revisa la membresía.',details:validation.errors});try{const [users]=await pool.execute("SELECT id FROM users WHERE email=? AND status='active' LIMIT 1",[validation.value.email]);if(!users[0])return res.status(404).json({error:'No existe un usuario activo con ese correo. Crea primero su cuenta mediante el proceso administrativo.'});const [result]=await pool.execute(`INSERT INTO company_memberships (company_id,user_id,role,status) VALUES (?,?,?,'active') ON DUPLICATE KEY UPDATE role=VALUES(role),status='active'`,[req.company.id,users[0].id,validation.value.role]);await audit(req,'membership.saved','user',users[0].id);return res.status(result.affectedRows===1?201:200).json({message:'Membresía guardada.',userId:users[0].id});}catch(error){return next(error);}});

router.put('/memberships/:userId',verifyCsrf,async(req,res,next)=>{const validation=validateMembership({email:'member@example.com',role:req.body.role,status:req.body.status});if(validation.errors)return res.status(422).json({error:'Revisa la membresía.',details:validation.errors});const userId=Number(req.params.userId);if(!Number.isSafeInteger(userId)||userId<1)return res.status(404).json({error:'Membresía no encontrada.'});const connection=await pool.getConnection();try{await connection.beginTransaction();const [rows]=await connection.execute('SELECT role,status FROM company_memberships WHERE company_id=? AND user_id=? FOR UPDATE',[req.company.id,userId]);if(!rows[0]){await connection.rollback();return res.status(404).json({error:'Membresía no encontrada.'});}const removesAdministrator=rows[0].role==='administrator'&&rows[0].status==='active'&&(validation.value.role!=='administrator'||validation.value.status!=='active');if(removesAdministrator){const [[count]]=await connection.execute("SELECT COUNT(*) AS total FROM company_memberships WHERE company_id=? AND role='administrator' AND status='active' AND user_id<>?",[req.company.id,userId]);if(!Number(count.total)){await connection.rollback();return res.status(409).json({error:'La empresa debe conservar al menos un administrador activo.'});}}await connection.execute('UPDATE company_memberships SET role=?,status=? WHERE company_id=? AND user_id=?',[validation.value.role,validation.value.status,req.company.id,userId]);await connection.commit();await audit(req,'membership.updated','user',userId);return res.json({message:'Membresía actualizada.'});}catch(error){await connection.rollback();return next(error);}finally{connection.release();}});
module.exports=router;
