const express=require('express');
const pool=require('../config/database');
const {requireAuth,requireMfa,requireAdministrator,verifyCsrf}=require('../middleware/security');
const {validateCompany,validateMembership}=require('../validation/administration');
const audit=require('../services/audit');
const router=express.Router();
router.use(requireAuth,requireMfa,requireAdministrator);

router.get('/companies',async(req,res,next)=>{try{const [companies]=await pool.execute(`SELECT c.id,c.legal_name AS legalName,c.trade_name AS tradeName,c.ruc,c.dv,c.status,c.created_at AS createdAt,COUNT(CASE WHEN m.status='active' THEN 1 END) AS activeMembers FROM companies c LEFT JOIN company_memberships m ON m.company_id=c.id WHERE c.tenant_id=? GROUP BY c.id ORDER BY c.legal_name`,[req.company.tenantId]);return res.json({companies,activeCompanyId:req.company.id});}catch(error){return next(error);}});

router.post('/companies',verifyCsrf,async(req,res,next)=>{const validation=validateCompany(req.body);if(validation.errors)return res.status(422).json({error:'Revisa los datos de la empresa.',details:validation.errors});const v=validation.value,connection=await pool.getConnection();try{await connection.beginTransaction();const [result]=await connection.execute("INSERT INTO companies (tenant_id,legal_name,trade_name,ruc,dv,status) VALUES (?,?,?,?,?,'active')",[req.company.tenantId,v.legalName,v.tradeName,v.ruc,v.dv]);await connection.execute("INSERT INTO company_memberships (company_id,user_id,role,status) VALUES (?,?,'administrator','active')",[result.insertId,req.authUser.id]);await connection.commit();await audit(req,'company.created','company',result.insertId);return res.status(201).json({message:'Empresa creada. Ya puedes cambiar a ella desde el selector superior.',id:result.insertId});}catch(error){await connection.rollback();return next(error);}finally{connection.release();}});

router.get('/memberships',async(req,res,next)=>{try{const [memberships]=await pool.execute(`SELECT u.id AS userId,u.full_name AS fullName,u.email,m.role,m.status,m.created_at AS createdAt FROM company_memberships m JOIN users u ON u.id=m.user_id WHERE m.company_id=? ORDER BY u.full_name`,[req.company.id]);return res.json({memberships,company:{id:req.company.id,name:req.company.name}});}catch(error){return next(error);}});

router.post('/memberships',verifyCsrf,async(req,res,next)=>{const validation=validateMembership({...req.body,status:'active'});if(validation.errors)return res.status(422).json({error:'Revisa la membresía.',details:validation.errors});try{const [users]=await pool.execute("SELECT id FROM users WHERE email=? AND status='active' LIMIT 1",[validation.value.email]);if(!users[0])return res.status(404).json({error:'No existe un usuario activo con ese correo. Crea primero su cuenta mediante el proceso administrativo.'});const [result]=await pool.execute(`INSERT INTO company_memberships (company_id,user_id,role,status) VALUES (?,?,?,'active') ON DUPLICATE KEY UPDATE role=VALUES(role),status='active'`,[req.company.id,users[0].id,validation.value.role]);await audit(req,'membership.saved','user',users[0].id);return res.status(result.affectedRows===1?201:200).json({message:'Membresía guardada.',userId:users[0].id});}catch(error){return next(error);}});

router.put('/memberships/:userId',verifyCsrf,async(req,res,next)=>{const validation=validateMembership({email:'member@example.com',role:req.body.role,status:req.body.status});if(validation.errors)return res.status(422).json({error:'Revisa la membresía.',details:validation.errors});const userId=Number(req.params.userId);if(!Number.isSafeInteger(userId)||userId<1)return res.status(404).json({error:'Membresía no encontrada.'});const connection=await pool.getConnection();try{await connection.beginTransaction();const [rows]=await connection.execute('SELECT role,status FROM company_memberships WHERE company_id=? AND user_id=? FOR UPDATE',[req.company.id,userId]);if(!rows[0]){await connection.rollback();return res.status(404).json({error:'Membresía no encontrada.'});}const removesAdministrator=rows[0].role==='administrator'&&rows[0].status==='active'&&(validation.value.role!=='administrator'||validation.value.status!=='active');if(removesAdministrator){const [[count]]=await connection.execute("SELECT COUNT(*) AS total FROM company_memberships WHERE company_id=? AND role='administrator' AND status='active' AND user_id<>?",[req.company.id,userId]);if(!Number(count.total)){await connection.rollback();return res.status(409).json({error:'La empresa debe conservar al menos un administrador activo.'});}}await connection.execute('UPDATE company_memberships SET role=?,status=? WHERE company_id=? AND user_id=?',[validation.value.role,validation.value.status,req.company.id,userId]);await connection.commit();await audit(req,'membership.updated','user',userId);return res.json({message:'Membresía actualizada.'});}catch(error){await connection.rollback();return next(error);}finally{connection.release();}});
module.exports=router;
