const express=require('express');
const pool=require('../config/database');
const {requireAuth,requireMfa}=require('../middleware/security');
const router=express.Router();router.use(requireAuth,requireMfa);
router.get('/dashboard',async(req,res,next)=>{try{const companyId=req.company.id;const [[quotes],[orders],[receivables],[sales]]=await Promise.all([pool.execute("SELECT COUNT(*) total,SUM(status='pending_approval') pendingApproval,SUM(status='accepted') readyToConvert,SUM(status IN ('draft','pending_approval','approved','sent','viewed','accepted')) openCount FROM crm_quotes WHERE company_id=?",[companyId]),pool.execute("SELECT COUNT(*) total,SUM(status='confirmed') confirmed,SUM(status='partially_invoiced') partiallyInvoiced FROM sales_orders WHERE company_id=?",[companyId]),pool.execute("SELECT COUNT(*) total,COALESCE(SUM(balance),0) balance,SUM(status='overdue') overdue FROM accounts_receivable WHERE company_id=? AND status IN ('pending','partial','overdue')",[companyId]),pool.execute("SELECT COUNT(*) documents,COALESCE(SUM(total),0) total FROM electronic_invoices WHERE company_id=? AND status='authorized' AND created_at>=DATE_FORMAT(CURRENT_DATE,'%Y-%m-01')",[companyId])]);return res.json({quotes:quotes[0],orders:orders[0],receivables:receivables[0],sales:sales[0]});}catch(error){return next(error);}});
router.get('/orders',async(req,res,next)=>{try{const [orders]=await pool.execute(`SELECT so.id,so.order_number AS orderNumber,so.status,so.currency,so.subtotal,so.discount_total AS discountTotal,so.tax_total AS taxTotal,so.total,so.created_at AS createdAt,so.source_quote_id AS sourceQuoteId,q.quote_number AS quoteNumber,q.version AS quoteVersion,c.legal_name AS clientName,o.title AS opportunityTitle FROM sales_orders so JOIN crm_quotes q ON q.id=so.source_quote_id JOIN clients c ON c.id=so.client_id LEFT JOIN crm_opportunities o ON o.id=so.opportunity_id WHERE so.company_id=? ORDER BY so.created_at DESC LIMIT 300`,[req.company.id]);return res.json({orders});}catch(error){return next(error);}});
router.get('/orders/:id',async(req,res,next)=>{try{const [[order]]=await pool.execute(`SELECT so.id,so.order_number AS orderNumber,so.status,so.currency,so.subtotal,so.discount_total AS discountTotal,so.tax_total AS taxTotal,so.total,so.created_at AS createdAt,so.customer_snapshot AS customerSnapshot,q.quote_number AS quoteNumber,q.version AS quoteVersion,c.legal_name AS clientName FROM sales_orders so JOIN crm_quotes q ON q.id=so.source_quote_id JOIN clients c ON c.id=so.client_id WHERE so.id=? AND so.company_id=?`,[req.params.id,req.company.id]);if(!order)return res.status(404).json({error:'Pedido no encontrado.'});const [items]=await pool.execute('SELECT sku,unit,description,quantity,unit_price AS unitPrice,discount_amount AS discountAmount,tax_code AS taxCode,subtotal,tax_amount AS taxAmount,line_total AS lineTotal FROM sales_order_items WHERE sales_order_id=? ORDER BY id',[order.id]);return res.json({order:{...order,items}});}catch(error){return next(error);}});
router.get('/orders/:id/invoice-draft',async(req,res,next)=>{try{const [[order]]=await pool.execute("SELECT source_quote_id AS sourceQuoteId FROM sales_orders WHERE id=? AND company_id=? AND status IN ('confirmed','partially_invoiced')",[req.params.id,req.company.id]);if(!order)return res.status(409).json({error:'El pedido no está disponible para facturación.'});return res.redirect(307,`/api/quotations/${order.sourceQuoteId}/invoice-draft`);}catch(error){return next(error);}});
module.exports=router;
