const express=require('express');
const crypto=require('node:crypto');
const bcrypt=require('bcryptjs');
const pool=require('../config/database');
const env=require('../config/env');
const audit=require('../services/audit');
const {requireAuth,requireMfa,requireAdministrator,requireRecentMfa,verifyCsrf}=require('../middleware/security');
const {validateManagedUser}=require('../validation/user-administration');
const router=express.Router();router.use(requireAuth,requireMfa,requireAdministrator);

router.get('/',async(req,res,next)=>{try{const [users]=await pool.execute(`SELECT u.id,u.full_name AS fullName,u.email,u.status AS accountStatus,u.mfa_enabled AS mfaEnabled,u.last_login_at AS lastLoginAt,m.role,m.status AS accessStatus,m.created_at AS createdAt FROM company_memberships m JOIN users u ON u.id=m.user_id WHERE m.company_id=? ORDER BY u.full_name`,[req.company.id]);return res.json({users,company:{id:req.company.id,name:req.company.name}});}catch(error){return next(error);}});
router.use((req,res,next)=>{if(req.body?.role==='administrator'&&!req.authUser.is_superuser)return res.status(403).json({error:'Solo el superusuario puede asignar administradores de empresa.'});return next();});
router.use(async(req,res,next)=>{if(req.method!=='PUT'||req.authUser.is_superuser)return next();try{const id=Number(req.path.slice(1));if(!Number.isSafeInteger(id))return next();const [rows]=await pool.execute('SELECT role FROM company_memberships WHERE company_id=? AND user_id=? LIMIT 1',[req.company.id,id]);if(rows[0]?.role==='administrator')return res.status(403).json({error:'Solo el superusuario puede modificar administradores de empresa.'});return next();}catch(error){return next(error);}});
router.use(verifyCsrf,requireRecentMfa);

router.post('/invite',verifyCsrf,async(req,res,next)=>{const validation=validateManagedUser({...req.body,status:'active'});if(validation.errors)return res.status(422).json({error:'Revisa los datos del usuario.',details:validation.errors});const v=validation.value,connection=await pool.getConnection();try{await connection.beginTransaction();const [found]=await connection.execute('SELECT id,status FROM users WHERE email=? LIMIT 1',[v.email]);let userId=found[0]?.id,token=null;if(!userId){const placeholder=await bcrypt.hash(crypto.randomBytes(32).toString('hex'),12);const [created]=await connection.execute("INSERT INTO users (full_name,email,password_hash,role,status) VALUES (?,?,?,?,'pending')",[v.fullName,v.email,placeholder,v.role]);userId=created.insertId;}await connection.execute("INSERT INTO company_memberships (company_id,user_id,role,status) VALUES (?,?,?,'active') ON DUPLICATE KEY UPDATE role=VALUES(role),status='active'",[req.company.id,userId,v.role]);if(!found[0]||found[0].status==='pending'){token=crypto.randomBytes(32).toString('hex');const hash=crypto.createHash('sha256').update(token).digest('hex');await connection.execute('UPDATE user_invitations SET used_at=UTC_TIMESTAMP() WHERE user_id=? AND used_at IS NULL',[userId]);await connection.execute('INSERT INTO user_invitations (user_id,company_id,token_hash,expires_at,created_by) VALUES (?,?,?,DATE_ADD(UTC_TIMESTAMP(),INTERVAL 48 HOUR),?)',[userId,req.company.id,hash,req.authUser.id]);}await connection.commit();await audit(req,token?'user.invited':'user.membership_added','user',userId);return res.status(201).json({message:token?'Invitación creada. El enlace se muestra una sola vez.':'El usuario existente fue agregado a la empresa.',userId,invitationUrl:token?`${env.appPublicUrl}/invite.html?token=${token}`:null});}catch(error){await connection.rollback();if(error.code==='ER_DUP_ENTRY')return res.status(409).json({error:'El correo ya está registrado.'});return next(error);}finally{connection.release();}});

router.put('/:id',verifyCsrf,async(req,res,next)=>{const validation=validateManagedUser(req.body);if(validation.errors)return res.status(422).json({error:'Revisa los datos del usuario.',details:validation.errors});const id=Number(req.params.id),v=validation.value;if(!Number.isSafeInteger(id)||id<1)return res.status(404).json({error:'Usuario no encontrado.'});if(id===Number(req.authUser.id)&&v.status==='suspended')return res.status(409).json({error:'No puedes suspender tu propio acceso.'});const connection=await pool.getConnection();try{await connection.beginTransaction();const [membership]=await connection.execute('SELECT role,status FROM company_memberships WHERE company_id=? AND user_id=? FOR UPDATE',[req.company.id,id]);if(!membership[0]){await connection.rollback();return res.status(404).json({error:'Usuario no encontrado en la empresa activa.'});}const removesAdmin=membership[0].role==='administrator'&&membership[0].status==='active'&&(v.role!=='administrator'||v.status!=='active');if(removesAdmin){const [[count]]=await connection.execute("SELECT COUNT(*) AS total FROM company_memberships WHERE company_id=? AND role='administrator' AND status='active' AND user_id<>?",[req.company.id,id]);if(!Number(count.total)){await connection.rollback();return res.status(409).json({error:'La empresa debe conservar al menos un administrador activo.'});}}await connection.execute('UPDATE users SET full_name=?,email=?,role=? WHERE id=?',[v.fullName,v.email,v.role,id]);await connection.execute('UPDATE company_memberships SET role=?,status=? WHERE company_id=? AND user_id=?',[v.role,v.status,req.company.id,id]);await connection.commit();await audit(req,'user.updated','user',id);return res.json({message:v.status==='suspended'?'Acceso suspendido sin eliminar el usuario.':'Usuario actualizado.'});}catch(error){await connection.rollback();if(error.code==='ER_DUP_ENTRY')return res.status(409).json({error:'El correo ya está registrado.'});return next(error);}finally{connection.release();}});

router.post('/:id/revoke-sessions',verifyCsrf,async(req,res,next)=>{const id=Number(req.params.id);try{const [membership]=await pool.execute('SELECT 1 FROM company_memberships WHERE company_id=? AND user_id=?',[req.company.id,id]);if(!membership[0])return res.status(404).json({error:'Usuario no encontrado.'});await pool.execute('UPDATE users SET auth_version=auth_version+1 WHERE id=?',[id]);await audit(req,'user.sessions_revoked','user',id);return res.json({message:'Todas las sesiones del usuario fueron revocadas.'});}catch(error){return next(error);}});
module.exports=router;
