const crypto=require('node:crypto');
const {validateClient}=require('../../../validation/client');
const ApplicationError=require('../../../shared/errors/application-error');
const normalizeRuc=value=>String(value||'').toUpperCase().replace(/[^A-Z0-9]/g,'');
const RULES_VERSION='clients-v1',MAPPING_VERSION='zoho-clients-v1';
const hash=file=>crypto.createHash('sha256').update(file.buffer).digest('hex');
function createClientImport({repository,fileParser,audit}){
 async function prepare(companyId,file){if(!file)throw new ApplicationError('Selecciona el archivo exportado por Zoho Invoice.',{status:422,code:'IMPORT_FILE_REQUIRED'});let parsed;try{parsed=fileParser.parse(file);}catch(error){throw new ApplicationError(error.message,{status:422,code:'INVALID_IMPORT_FILE'});}const valid=[],invalid=[];for(const item of parsed){const validation=validateClient(item.client);if(validation.errors)invalid.push({row:item.sourceRow,name:item.client.legalName||'Sin nombre',errors:validation.errors});else valid.push({...item,client:validation.value});}const existing=await repository.identities(companyId),seenRucs=new Map(existing.filter(x=>x.ruc).map(x=>[normalizeRuc(x.ruc),x])),seenCodes=new Map(existing.filter(x=>x.code).map(x=>[x.code,x])),seenEmails=new Map(existing.filter(x=>x.email).map(x=>[x.email.toLowerCase(),x])),duplicates=[],ready=[];for(const item of valid){const v=item.client,ruc=normalizeRuc(v.ruc),duplicate=(ruc&&seenRucs.get(ruc))||(v.code&&seenCodes.get(v.code))||(v.email&&seenEmails.get(v.email.toLowerCase()));if(duplicate)duplicates.push({row:item.sourceRow,name:v.legalName,ruc:v.ruc,existingId:duplicate.id||null});else{ready.push(item);const marker={id:null};if(ruc)seenRucs.set(ruc,marker);if(v.code)seenCodes.set(v.code,marker);if(v.email)seenEmails.set(v.email.toLowerCase(),marker);}}const summary={total:parsed.length,ready:ready.length,duplicates:duplicates.length,invalid:invalid.length,warnings:parsed.filter(i=>i.warnings.length).length};return{ready,duplicates,invalid,summary};}
 return{async preview({companyId,actorUserId,file}){const x=await prepare(companyId,file),importJobId=crypto.randomUUID();await repository.createImportJob({id:importJobId,companyId,userId:actorUserId,fileHash:hash(file),rulesVersion:RULES_VERSION,mappingVersion:MAPPING_VERSION,summary:x.summary,idempotencyKey:importJobId});return{importJobId,expiresInSeconds:1800,summary:x.summary,preview:x.ready.slice(0,100).map(i=>({row:i.sourceRow,name:i.client.legalName,email:i.client.email,ruc:i.client.ruc,customerType:i.client.customerType,warnings:i.warnings})),duplicates:x.duplicates.slice(0,50),invalid:x.invalid.slice(0,50)};},async confirm({companyId,actorUserId,file,importJobId,auditContext}){if(!/^[0-9a-f-]{36}$/i.test(importJobId||''))throw new ApplicationError('La confirmación requiere el import_job_id de la vista previa.',{status:422,code:'IMPORT_JOB_REQUIRED'});const x=await prepare(companyId,file),completed=await repository.completeImportJob({companyId,userId:actorUserId,id:importJobId,fileHash:hash(file),rulesVersion:RULES_VERSION,summary:x.summary,clients:x.ready.map(i=>i.client)});if(completed.kind==='missing')throw new ApplicationError('La vista previa no pertenece al usuario o empresa activa.',{status:404,code:'IMPORT_JOB_NOT_FOUND'});if(completed.kind==='expired')throw new ApplicationError('La vista previa expiró; analiza nuevamente el archivo.',{status:409,code:'IMPORT_JOB_EXPIRED'});if(completed.kind==='changed')throw new ApplicationError('El archivo, las reglas o el resultado cambiaron desde la vista previa.',{status:409,code:'IMPORT_PREVIEW_CHANGED'});if(completed.kind!=='replay')await audit({...auditContext,actorUserId,companyId,action:'clients.zoho_imported',targetType:'import_job',targetId:null});return{message:`${completed.result.imported} clientes importados.`,replayed:completed.kind==='replay',summary:completed.result};}};
}
module.exports={createClientImport,RULES_VERSION,MAPPING_VERSION};
