const express=require('express');
const {requireAuth,requireMfa,requireAdministrator,verifyCsrf}=require('../../middleware/security');
const {singleMemoryFile}=require('../../middleware/multipart');
const controller=require('./clients.composition');
const uploadZohoFile=singleMemoryFile('file',{fileSize:5*1024*1024}),router=express.Router();
router.use(requireAuth,requireMfa);
router.get('/custom-fields',controller.listFields);
router.post('/custom-fields',requireAdministrator,verifyCsrf,controller.createField);
router.post('/import/zoho',requireAdministrator,verifyCsrf,uploadZohoFile,controller.importZoho);
router.get('/',controller.list);
router.post('/',verifyCsrf,controller.create);
router.get('/:id',controller.get);
router.put('/:id',verifyCsrf,controller.update);
module.exports=router;
