const path=require('node:path');
const crypto=require('node:crypto');
const express=require('express');
const helmet=require('helmet');
const compression=require('compression');
const session=require('express-session');
const MySQLStoreFactory=require('express-mysql-session');
const {rateLimit}=require('express-rate-limit');
const env=require('./config/env');
const pool=require('./config/database');
const {issueCsrfToken,requireAuth,requireMfa}=require('./middleware/security');
const {observeRequest,renderMetrics}=require('./services/metrics');

function createApp(dependencies={}){const database=dependencies.pool||pool,app=express();if(env.trustProxy)app.set('trust proxy',env.trustProxy);app.disable('x-powered-by');app.use((req,res,next)=>{req.requestId=crypto.randomUUID();res.setHeader('x-request-id',req.requestId);next();});app.use(observeRequest);app.use(helmet({contentSecurityPolicy:{directives:{defaultSrc:["'self'"],scriptSrc:["'self'"],styleSrc:["'self'",'https://fonts.googleapis.com'],fontSrc:["'self'",'https://fonts.gstatic.com'],imgSrc:["'self'",'data:'],objectSrc:["'none'"],frameAncestors:["'none'"]}}}));app.use(compression());app.use(express.json({limit:'32kb',strict:true}));
const MySQLStore=MySQLStoreFactory(session),sessionStore=dependencies.sessionStore||new MySQLStore({...env.db,createDatabaseTable:true,schema:{tableName:'user_sessions',columnNames:{session_id:'session_id',expires:'expires',data:'data'}}});app.use(session({name:'factura.sid',secret:env.sessionSecret,store:sessionStore,resave:false,saveUninitialized:false,rolling:true,cookie:{httpOnly:true,secure:env.isProduction,sameSite:'lax',maxAge:8*60*60*1000}}));
const limiter=(windowMs,limit,message)=>rateLimit({windowMs,limit,standardHeaders:'draft-8',legacyHeaders:false,message:{error:message}}),loginLimiter=limiter(15*60*1000,10,'Demasiados intentos. Espera unos minutos.'),resetLimiter=limiter(60*60*1000,5,'Demasiadas solicitudes. Espera antes de intentarlo nuevamente.'),configLimiter=limiter(15*60*1000,10,'Demasiados cambios de configuración. Espera unos minutos.');app.get('/api/csrf-token',issueCsrfToken);app.use('/api/auth/login',loginLimiter);app.use('/api/auth/password/forgot',resetLimiter);app.use('/api/auth/password/reset',resetLimiter);app.use('/api/auth',require('./routes/auth'));app.use('/api/config',configLimiter,require('./routes/configuration'));app.use('/api/invoices',require('./modules/invoicing/invoices.routes'));app.use('/api/clients',require('./routes/clients'));app.use('/api/articles',require('./routes/articles'));app.use('/api/administration',require('./routes/administration'));app.use('/api/users',require('./routes/users'));app.use('/api/crm',require('./routes/crm-advanced'));app.use('/api/crm',require('./routes/crm'));app.get('/api/health/live',(_req,res)=>res.json({status:'ok'}));app.get(['/api/health','/api/health/ready'],async(_req,res)=>{try{await database.query('SELECT 1');res.json({status:'ok',checks:{database:'ok'}});}catch{res.status(503).json({status:'degraded',checks:{database:'failed'}});}});app.get('/internal/metrics',(req,res)=>{const expected=Buffer.from(env.observabilityToken),received=Buffer.from(String(req.get('authorization')||'').replace(/^Bearer\s+/i,''));if(!expected.length||expected.length!==received.length||!crypto.timingSafeEqual(expected,received))return res.status(401).type('text').send('Unauthorized\n');return res.type('text/plain; version=0.0.4').send(renderMetrics());});app.get(['/dashboard','/dashboard.html'],requireAuth,requireMfa,(_req,res)=>res.sendFile(path.join(__dirname,'..','public','dashboard.html')));app.use(express.static(path.join(__dirname,'..','public'),{extensions:['html'],maxAge:env.isProduction?'1h':0}));app.use('/api',(_req,res)=>res.status(404).json({error:'Ruta no encontrada.'}));app.use((error,req,res,_next)=>{console.error(JSON.stringify({event:'request_failed',requestId:req.requestId,error:error.message}));if(!res.headersSent)res.status(error.status||500).json({error:error.expose?error.message:'Ocurrió un error interno.'});});return app;}
module.exports={createApp};
